spring:
  application:
    name: server
  datasource:
    # 这里的 distribution_system 必须是你 MySQL 中实际存在的数据库名
    url: jdbc:mysql://localhost:3306/distribution_system?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456 # 请确认这是你的 MySQL 密码
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis-Plus 相关配置
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 3000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

oss:
  endpoint: oss-cn-beijing.aliyuncs.com
  accessKeyId: ${ALI_ACCESS_KEY_ID}
  accessKeySecret: ${ALI_ACCESS_KEY_SECRET}
  bucketName: dist-system-img